# Generated by Django 5.0.6 on 2024-07-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('deleted', 'Удаленная')], default='new', max_length=25, verbose_name='Статус'),
        ),
    ]
