# Generated by Django 5.0.6 on 2024-07-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'db_table': 'sections',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_at',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('deleted', 'Удаленная')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='webapp.section', verbose_name='Секция'),
            preserve_default=False,
        ),
    ]
